### ISSUE TITLE
again

### ISSUE THREAD

**Issue by obileuser** [0BunnySenpai0/ProdigyHacking--MobileHacking#35]
***What items should be in the account?***: Everything

***What level do you want, how much gold, dark tower floor, etc?***: max level max dark tower floor max everything

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:Icedragonvsfiredragon7@gmail.com 

also if it can be a member plz and the battle fix and everything and can my name be MatteoMoonbringer thank you so much

**Comment by obileuser** [comment]
oh and all pets

**Comment by Prodigy-hack-yt** [comment]
Did i send you stuff for this one

**Comment by obileuser** [comment]
what sorry I was eating?

**Comment by ShawnC32** [comment]
[https://github.com/ShawnC32/Prodigy-Provider](url)
Check out prodigy provider
