### ISSUE TITLE
Account Request

### ISSUE THREAD

**Issue by jakepressley08** [0BunnySenpai0/ProdigyHacking--MobileHacking#50]
***I Want all the items in the game on the account***:

***level 100 gold 9999999999 and everything else max or 9999999999***:

***jpressley9320@cabarrus.k12.nc.us***:

**Comment by jakepressley08** [comment]
can u get it done by a hour or 2
________________________________

**Comment by jakepressley08** [comment]
Do you need a login to a existing prodigy account to start the procces or do you just make one your self and do it from there like i told u earlier to do
________________________________

**Comment by SakuraKitsunee** [comment]
yeah I can make it myself

**Comment by jakepressley08** [comment]
is it done
________________________________
