### ISSUE TITLE
Can I have a account please

### ISSUE THREAD

**Issue by obileuser** [0BunnySenpai0/ProdigyHacking--MobileHacking#53]
***What items should be in the account?***: Everything and all pets

***What level do you want, how much gold, dark tower floor, etc?***:Max level Max Max dark tower floor

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***: icedragonvsfiredragon7@gmail.com

Thank you so much

**Comment by likaij** [comment]
hi

**Comment by 0BunnySenpai0** [comment]
@obileuser do you still want an account???
