### ISSUE TITLE
Account Request

### ISSUE THREAD

**Issue by ThatLegend** [0BunnySenpai0/ProdigyHacking--MobileHacking#54]
***What items should be in the account?***:
All Items
***What level do you want, how much gold, dark tower floor, etc?***:
E+29 gold level 100 dark tower 100
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:
Denboysib@gmail.com

**Comment by SakuraKitsunee** [comment]
@ThatLegend what do you want your in game name too be?

**Comment by ThatLegend** [comment]
Super king

**Comment by likaij** [comment]
ohh me pless

**Comment by likaij** [comment]
mimbership and level ablove 100 or the max you can go everything gold wands etc dark tower max lilkaiclips@gmail.com pls
