### ISSUE TITLE
account request

### ISSUE THREAD

**Issue by mahki2002** [0BunnySenpai0/ProdigyHacking--MobileHacking#56]
***What items should be in the account?***:
all of them pls
***What level do you want, how much gold, dark tower floor, etc?***:
max everything, max level, max level pets 
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***: deadpoolkain23@outlook.com

**Comment by SakuraKitsunee** [comment]
@mahki2002 do you still want a account?, also sorry for the long response I have been kinda busy with school!

**Comment by mahki2002** [comment]
yesssssssss
