### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by coolman3289** [0BunnySenpai0/ProdigyHacking--MobileHacking#58]
***What items should be in the account?***:
All
***What level do you want, how much gold, dark tower floor, etc?***:
Max all
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:
Zaqtest1@gmail.com

**Comment by 0BunnySenpai0** [comment]
@coolman3289 im about to send you your prodigy account check your email!
