### ISSUE TITLE
Account Request Monday January 10, 2022

### ISSUE THREAD

**Issue by Seeker-Of-Knowledge** [0BunnySenpai0/ProdigyHacking--MobileHacking#59]
***What items should be in the account?***:
If you could every item + pet
***What level do you want, how much gold, dark tower floor, etc?***:
Level 60 , 1000k gold, 1 dark floor tower,   Premium If you could.
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:

davidtheduck2@gmail.com

**Comment by 0BunnySenpai0** [comment]
@Seeker-Of-Knowledge do you still want me to make you this account???

**Comment by Seeker-Of-Knowledge** [comment]
yea sure

**Comment by 0BunnySenpai0** [comment]
ok  ill email it to you!

**Comment by 0BunnySenpai0** [comment]
@Seeker-Of-Knowledge just emailed
