### ISSUE TITLE
Hack Request

### ISSUE THREAD

**Issue by Gamercat121** [0BunnySenpai0/ProdigyHacking--MobileHacking#60]
***What items should be in the account?***: Full trialmaster's set, new epics.

***What level do you want, how much gold, dark tower floor, etc?***: Lv. 100, 1000000 gold, dark tower floor 1.

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***: 460407@bsd48.org

**Comment by 0BunnySenpai0** [comment]
@Gamercat121 im making your account right now

**Comment by 0BunnySenpai0** [comment]
@Gamercat121 emailing you your account info

**Comment by 0BunnySenpai0** [comment]
@Gamercat121  done
