### ISSUE TITLE
Mod Application

### ISSUE THREAD

**Issue by Seeker-Of-Knowledge** [0BunnySenpai0/ProdigyHacking--MobileHacking#62]
1. Do you want to be a mod?

yes (X)

No ()

2. do you have past experience with being a mod for other things (github,websites etc.) 

yes (X)

No ()

3. What makes you more suitable over other candidates?

I am an extremely efficient worker. I am know for being a fast  worker who is good with people. I have achieved a beginner level in Javascript as well. I know how to get the Job done!

**Comment by SakuraKitsunee** [comment]
okay....

**Comment by SakuraKitsunee** [comment]
your accepted!!!

**Comment by Seeker-Of-Knowledge** [comment]
Tell me how I can help!

**Comment by SakuraKitsunee** [comment]
well here first let mke promote you check your email

**Comment by 0BunnySenpai0** [comment]
@Seeker-Of-Knowledge did you get a email yet?

**Comment by Seeker-Of-Knowledge** [comment]
Yep, I accepted the Invite

**Comment by 0BunnySenpai0** [comment]
ok

**Comment by 0BunnySenpai0** [comment]
whats your email, im going to email you the online prodigy mod menu

**Comment by Seeker-Of-Knowledge** [comment]
davidtheduck2@gmail.com

**Comment by 0BunnySenpai0** [comment]
can you accept the hangout too

**Comment by Seeker-Of-Knowledge** [comment]
Sure

**Comment by Seeker-Of-Knowledge** [comment]
I´m In
