### ISSUE TITLE
pls

### ISSUE THREAD

**Issue by mahki2002** [0BunnySenpai0/ProdigyHacking--MobileHacking#63]
***What items should be in the account?***:
everything
***What level do you want, how much gold, dark tower floor, etc?***:
max everything
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:
deadpoolkain23@outlook.com

**Comment by 0BunnySenpai0** [comment]
@mahki2002 about to email you the account !!! :)
