### ISSUE TITLE
I want hacked acc pls URGENT x999999999999999999999999999999 VERY URGENT

### ISSUE THREAD

**Issue by chenkevin66** [0BunnySenpai0/ProdigyHacking--MobileHacking#71]
***What items should be in the account?***:
Everything. 1e+69 of everything + all the buddies + pets. 100,000 of all currencies and the gold still 1,000,000 ever other currencies are 100,000. + Ultimate Membership. all runes all relics. All the pets should be level 1000 if possible if not possible then 100 level and max everything. JUST USE ALL THE HACKS AND IF THERE IS AN INPUT JUST PUT IN THE MAX
***What level do you want, how much gold, dark tower floor, etc?***:
I want level 1000 if possible if not lv 100. dark tower floor 100, gold = 6,779,754
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is calebthehufflepuff@gmail.com)***:
ok I will send my email to you. My subject will be hihihihihihiihihihihihihihiprodigyhackspls. Tho if u lost access to ur email its chenkevin66@protonmail.com.

**Comment by chenkevin66** [comment]
### aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by chenkevin66** [comment]
@SakuraKitsunee Are you a staff member? If so please answer my question above/do accordingly

**Comment by jakepressley08** [comment]
Sorry for the wait you need to be patient you need to recognize that we have other people that want the same as you
________________________________

**Comment by chenkevin66** [comment]
Okey, SOrry.

**Comment by 0BunnySenpai0** [comment]
@chenkevin66  sorry for the wait do you still want a account?

**Comment by chenkevin66** [comment]
Yes

**Comment by chenkevin66** [comment]
I do

**Comment by chenkevin66** [comment]
Your team doesn't fucking give accounts even tho you fucking ask if you still want an account. You guys are a fucking piece of shit I will never recommend your team to my friends.

**Comment by chenkevin66** [comment]
I can't even lock the conversation!?!?!? Shit

**Comment by chenkevin66** [comment]
Okey people... FUCKING DON'T FUCKING TALK TO ME ANYMORE
